openapi: 3.0.2
info:
  title: CoopCare API
  version: 0.0.1
  contact:
    name: slowtec GmbH
    url: 'https://slowtec.de'
servers:
  - url: 'http://localhost:8888/v0/'
    description: Test server

paths:
  /clients:
    get:
      description: Get all clients
      operationId: app.get_clients
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'

  /client/{clientId}/problems:
    get:
      description: Get client's problems
      operationId: app.get_client_problems
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProblemClassification'
    post:
      description: Create a new problem
      operationId: app.post_client_problems
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
      requestBody:
        description: new problem
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProblemClassification'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProblemClassification'

  /client/{clientid}/problem/{problemid}/interventions:
    get:
      description: get interventions
      operationId: app.get_client_problem_interventions
      parameters:
        - name: clientid
          in: path
          required: true
          schema:
            type: integer
        - name: problemid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
  /client/{clientId}/problem/{problemId}/ratings:
    get:
      description: Get problem ratings
      operationId: app.get_client_problem_ratings
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: integer
        - name: problemId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
  
  /omaha/intervention_categories:
    get:
      description: Get Omaha intervention categories
      operationId: app.get_omaha_intervention_categories
      parameters:
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OmahaInterventionCategory'
  /omaha/intervention_targets:
    get:
      description: Get Omaha intervention targets
      operationId: app.get_omaha_intervention_targets
      parameters:
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OmahaInterventionTarget'
  /omaha/problem_domains:
    get:
      description: Get Omaha problem domain catalog
      operationId: app.get_omaha_problem_domains
      parameters:
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OmahaProblemDomain'
  /omaha/problems:
    get:
      description: Get Omaha problem catalog
      operationId: app.get_omaha_problems
      parameters:
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OmahaProblem'
  /omaha/symptoms:
    get:
      description: Get Omaha symptom catalog
      operationId: app.get_omaha_symptoms
      parameters:
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OmahaSymptom'
components:
  schemas:
    Client:
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Intervention:
      required:
        - categoryId
        - targetId
        - description
      properties:
        categoryId:
          $ref: '#/components/schemas/CategoryId'
        targetId:
          $ref: '#/components/schemas/TargetId'
        description:
          type: string
    OmahaInterventionCategory:
      required:
        - id
        - title
        - description
      properties:
        id:
          $ref: '#/components/schemas/CategoryId'
        title:
          type: string
        description:
          type: string
    OmahaInterventionTarget:
      required:
        - id
        - title
        - description
      properties:
        id:
          $ref: '#/components/schemas/TargetId'
        title:
          type: string
        description:
          type: string
    OmahaProblemDomain:
      required:
        - id
        - title
        - description
      properties:
        id:
          $ref: '#/components/schemas/DomainId'
        title:
          type: string
        description:
          type: string
    OmahaProblem:
      required:
        - id
        - title
        - description
        - domainId
      properties:
        id:
          $ref: '#/components/schemas/ProblemId'
        title:
          type: string
        description:
          type: string
        domainId:
          $ref: '#/components/schemas/DomainId'
    OmahaSymptom:
      required:
        - id
        - title
        - domainId
        - problemId
      properties:
        id:
          $ref: '#/components/schemas/SymptomId'
        title:
          type: string
        domainId:
          $ref: '#/components/schemas/DomainId'
        problemId:
          $ref: '#/components/schemas/ProblemId'
    ProblemClassification:
      required:
        - problemId
        - domainModifier
        - typeModifier
        - symptoms
        - interventions
        - comment
      properties:
        problemId:
          $ref: '#/components/schemas/ProblemId'
        domainModifier:
          $ref: '#/components/schemas/ProblemDomainModifier'
        typeModifier:
          $ref: '#/components/schemas/ProblemTypeModifier'
        symptoms:
          type: array
          items:
            $ref: '#/components/schemas/SymptomId'
        interventions:
          type: array
          items:
            $ref: '#/components/schemas/Intervention'
        ratings:
          type: array
          items:
            $ref: '#/components/schemas/Rating'
        comment:
          type: string
    ProblemDomainModifier:
      type: string
      enum:
        - individual
        - family
        - community
    ProblemTypeModifier:
      type: string
      enum:
        - health-promotion
        - potential
        - actual
    Rating:
      required:
        - created
        - currentState
      properties:
        created:
          $ref: '#/components/schemas/Timestamp'
        currentState:
          $ref: '#/components/schemas/RatingScale'
        goalState:
          $ref: '#/components/schemas/RatingScale'
        comment:
          type: string
    RatingScale:
      required:
        - status
        - knowledge
        - behaviour
      properties:
        status:
          type: integer
        knowledge:
          type: integer
        behaviour:
          type: integer
        statusComment:
          type: string
        knowledgeComment:
          type: string
        behaviourComment:
          type: string
    Timestamp:
      type: string
      format: date-time
    CategoryId:
      type: string
      pattern: 'C\d\d'
      example: 'C02'
    TargetId:
      type: string
      pattern: 'T\d\d'
      example: 'T32'
    DomainId:
      type: string
      pattern: 'D\d\d'
      example: 'D02'
    ProblemId:
      type: string
      pattern: 'D\d\dP\d\d'
      example: 'D01P01'
    SymptomId:
      type: string
      pattern: 'D\d\dP\d\dS\d\d'
      example: 'D03P04S02'
  parameters:
    langParam:
      name: lang
      in: query
      required: false
      schema:
        type: string
        enum:
          - EN
          - DE
    clientIdParam:
      name: clientId
      in: path
      required: true
      schema:
        type: integer

